apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-gateway
  labels:
    name: orders-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      name: orders-gateway
  template:
    metadata:
      labels:
        name: orders-gateway
    spec:
      containers:
        - name: orders-gateway
          image: repo.orders.com:5000/orders/orders-gateway
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: peer1,prod
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-eureka-0.eureka-hl:8761/discovery/eureka/,http://discovery-eureka-1.eureka-hl:8761/discovery/eureka/
          ports:
            - containerPort: 8763

---
apiVersion: v1
kind: Service
metadata:
  name: orders-gateway-service
  labels:
    name: orders-gateway-service
spec:
  ports:
    - name: "8763"
      port: 8763
      targetPort: 8763
      nodePort: 31763
  selector:
    name: orders-gateway
  type: NodePort
status:
  loadBalancer: {}