apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"