apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-store-intra
  labels:
    name: orders-store-intra
spec:
  replicas: 2
  selector:
    matchLabels:
      name: orders-store-intra
  template:
    metadata:
      labels:
        name: orders-store-intra
    spec:
      dnsConfig:
        nameservers:
          - 192.168.249.2
          - 8.8.8.8
        searches:
          - demo.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "2"
          - name: edns0
      containers:
        - name: orders-store-intra
          image: repo.orders.com:5000/orders/orders-store-intra
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_HOST
              value: 'mysql-service.default.svc.cluster.local'
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-eureka-0.eureka-hl:8761/discovery/eureka/,http://discovery-eureka-1.eureka-hl:8761/discovery/eureka/
            - name: REMOTE_API_PRODUCT_URI
              value: http://product-service.default.svc.cluster.local:8082
            - name: REMOTE_API_ORDERS_URI
              value: http://orders-service.default.svc.cluster.local:8081

          ports:
            - containerPort: 8083
          volumeMounts:
            - name: logs
              mountPath: /logs
        - name: filebeat
          image: elastic/filebeat:7.10.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: /logs
            - name: config
              mountPath: /usr/share/filebeat/filebeat.yml
              readOnly: true
              subPath: filebeat.yml

      volumes:
        - name: logs
          emptyDir: {}
        - name: config
          configMap:
            defaultMode: 420
            name: filebeat-conf

---
apiVersion: v1
kind: Service
metadata:
  name: orders-store-intra-service
  labels:
    name: orders-store-intra-service
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
      nodePort: 30083
  selector:
    name: orders-store-intra
  type: NodePort
status:
  loadBalancer: {}